package io.mincong.immutables;

import java.util.Optional;
import java.util.Set;
import org.immutables.value.Value;

/**
 * User class (implementation is generated by framework: Immutables)
 *
 * @author Mincong Huang
 */
@Value.Immutable
public interface User {

  static ImmutableUser.Builder builder() {
    return ImmutableUser.builder();
  }

  String name();

  Set<String> emails();

  Optional<String> description();

}
