package io.mincong.immutables;

import java.util.Optional;
import java.util.Set;
import org.immutables.value.Value;

/**
 * User class (implementation is generated by framework: Immutables)
 *
 * @author Mincong Huang
 */
@Value.Immutable
public abstract class User {

  public static ImmutableUser.Builder builder() {
    return ImmutableUser.builder();
  }

  public abstract String name();

  public abstract Set<String> emails();

  public abstract Optional<String> description();

}
