language: java
jdk:
  - openjdk11
  - openjdk14
script:
  - mvn clean verify -Psonar
addons:
  sonarcloud:
    organization: 'mincong-h-github'
    token: $SONAR_TOKEN
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
