-- TODO rename "BONUSPAYOUT" to "DEMO"
CREATE TABLE "BONUSPAYOUT"."RECTANGLE" (
    "ID" INTEGER NOT NULL,
    "SURFACE" INTEGER NOT NULL
);

-- TODO rename "BONUSPAYOUT" to "DEMO"
ALTER TABLE "BONUSPAYOUT"."RECTANGLE"
ADD CONSTRAINT "RECTANGLE_PK" PRIMARY KEY ("ID");
